version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'


  scheduleDB:
    image: mysql
    container_name: 'schedule_sql_db'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduleDB
    ports:
      - '3306:3306'



volumes:
  mongo-volume:

