version: '3'
services:
  mongo1:
    image: 'mongo'
    container_name: 'mongo1'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./mongo1_volumes/data:/data/db

    ports:
      - '27017-27019:27017-27019'
