version: '3'
services:
  hallDB:
    image: 'mongo'
    container_name: 'hall_mongo_db'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017:27017'

  mediaDB:
    image: 'mongo'
    container_name: 'media_mongo_db'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    ports:
      - '27020:27017'

  scheduleDB:
    image: mysql:5.7
    container_name: 'schedule_sql_db'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduleDB
    expose:
      - '3308'
    ports:
      - '3308:3306'

  advertisementDB:
    image: mysql:5.7
    container_name: 'advertisement_sql_db'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: advertisementDB
    expose:
      - '3310'
    ports:
      - '3310:3306'

  staffDB:
    image: mysql:5.7
    container_name: 'staff_sql_db'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staffDB
    expose:
      - '3309'
    ports:
      - '3309:3306'

  ticketDB:
    image: mysql:5.7
    container_name: 'ticket_sql_db'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketDB
    expose:
      - "3307"
    ports:
      - '3307:3306'

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.100:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"

  staff:
    container_name: 'staff'
    build: ./bioscoop-app-staff-service
    links:
      - staffDB
      - schedule
    depends_on:
      - staffDB
      - schedule
    ports:
      - "2224:2224"
  schedule:
    container_name: 'schedule'
    build: ./bioscoop-app-schedule-service
    links:
      - scheduleDB
    depends_on:
      - scheduleDB
    ports:
      - "2223:2223"
  gateway:
    container_name: 'gateway'
    build: ./bioscoop-app-api-gateway
    links:
      - schedule
      - staff
    ports:
      - "3000:3000"

volumes:
  mongo-volume:

