version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
volumes:
  mongo-volume: